.PHONY: up down logs build test lint migrate new-migration psql dev-shell

up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f

build:
	docker compose build

test:
	docker compose run --rm jarvis-dev pytest

lint:
	docker compose run --rm jarvis-dev ruff check apps core database tests

migrate:
	docker compose exec jarvis-api alembic -c database/alembic.ini upgrade head

# Create a new autogenerated migration, e.g. `make new-migration name="add x"`
new-migration:
	docker compose run --rm jarvis-dev alembic -c database/alembic.ini revision --autogenerate -m "$(name)"

psql:
	docker compose exec postgres psql -U jarvis -d jarvis

dev-shell:
	docker compose run --rm jarvis-dev /bin/sh
